version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
  - package-ecosystem: mix
    directory: "/demo"
    schedule:
      interval: weekly
      day: saturday
  - package-ecosystem: npm
    directory: "/demo/assets"
    schedule:
      interval: weekly
      day: saturday
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
